version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'

  web:
    build: .
    command: sh -c "npm --prefix frontend install &&
                    npm --prefix frontend run build &&
                    python manage.py wait_for_db &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      # - static:/static
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache

#   nginx:
#     build: ./nginx
#     volumes:
#       - static:/static
#     ports: 
#       - "08:08"
#     depends_on:
#       - web


# volumes:
#   static: