# Generated by Django 4.0 on 2021-12-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=256)),
                ('received_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('spreading_factor', models.PositiveSmallIntegerField(default=None, null=True)),
                ('consumed_airtime', models.DecimalField(decimal_places=9, default=None, max_digits=15, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='UplinkGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.CharField(max_length=128)),
                ('gateway_eui', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rssi', models.SmallIntegerField(default=None, null=True)),
                ('snr', models.DecimalField(decimal_places=3, default=None, max_digits=9, null=True)),
                ('uplink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='sensor.uplink')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_dev_id', models.CharField(max_length=128)),
                ('activation_method', models.SmallIntegerField(blank=True, choices=[(0, 'OTAA'), (1, 'ABP')], null=True)),
                ('app_eui', models.CharField(max_length=64)),
                ('dev_eui', models.CharField(max_length=64)),
                ('app_key', models.CharField(max_length=64)),
                ('nwks_key', models.CharField(max_length=64)),
                ('apps_key', models.CharField(max_length=64)),
                ('dev_addr', models.CharField(max_length=64)),
                ('uplinks', models.ManyToManyField(blank=True, to='sensor.Uplink')),
            ],
        ),
    ]
