# Generated by Django 4.0 on 2021-12-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsensor',
            name='end_dev_id',
        ),
        migrations.AddField(
            model_name='roomsensor',
            name='device_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
