# Generated by Django 4.0 on 2022-01-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_remove_roomsensor_end_dev_id_roomsensor_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsensor',
            name='device_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roomsensor',
            name='device_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
