# Generated by Django 3.2.10 on 2022-01-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_roomsensor_device_description_roomsensor_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsensor',
            name='device_id',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
    ]
