# Generated by Django 3.2.10 on 2022-01-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_alter_roomsensor_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsensor',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
