# Generated by Django 3.2.10 on 2022-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_alter_roomsensor_device_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsensor',
            name='activation_method',
        ),
        migrations.RemoveField(
            model_name='roomsensor',
            name='app_eui',
        ),
        migrations.RemoveField(
            model_name='roomsensor',
            name='app_key',
        ),
        migrations.RemoveField(
            model_name='roomsensor',
            name='apps_key',
        ),
        migrations.RemoveField(
            model_name='roomsensor',
            name='dev_addr',
        ),
        migrations.RemoveField(
            model_name='roomsensor',
            name='dev_eui',
        ),
        migrations.RemoveField(
            model_name='roomsensor',
            name='nwks_key',
        ),
        migrations.AddField(
            model_name='roomsensor',
            name='display_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomsensor',
            name='display_temperature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomsensor',
            name='displayed_uplinks_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
