# Generated by Django 3.2.10 on 2022-02-04 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_auto_20220130_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDownlinksCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('downlink_count', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('room_sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_downlink_count', to='sensor.roomsensor')),
            ],
        ),
    ]
