# Generated by Django 3.2.10 on 2022-02-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_dailydownlinkscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.CharField(max_length=128)),
                ('gateway_eui', models.CharField(max_length=128)),
                ('uplinks', models.ManyToManyField(blank=True, to='sensor.Uplink')),
            ],
        ),
        migrations.DeleteModel(
            name='UplinkGateway',
        ),
    ]
