# Generated by Django 3.2.10 on 2022-02-14 16:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0008_auto_20220205_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxNotifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='', max_length=256, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=256)),
                ('device_description', models.TextField(blank=True)),
                ('is_mail', models.BooleanField(default=False)),
                ('number_of_mails', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('should_notify', models.BooleanField(default=False)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
            ],
        ),
    ]
