# Generated by Django 3.2.10 on 2022-02-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0009_mailboxnotifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailboxnotifier',
            name='is_mail',
        ),
    ]
