# Generated by Django 3.2.10 on 2022-02-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0010_remove_mailboxnotifier_is_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='', max_length=256, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=256)),
                ('device_description', models.TextField(blank=True)),
                ('uplinks', models.ManyToManyField(blank=True, to='sensor.Uplink')),
            ],
        ),
    ]
